# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bertvv/centos72"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provision :shell, path: "scriptLAMPstack.sh"  
  config.vm.provision :shell, path: "testappscript.sh"  
end
